### ISSUE TITLE
Invoice: không chấp nhận kí hiệu -, hoặc 0% ở lượng tiền VAT

### ISSUE THREAD

**Issue by neittien0110** [dylan751/sushi#204]
## Mô tả
 - Kí tự - có nghĩa là không có VAT là kí tự hợp lệ.
 - VAT 0% cũng phố biến.
 Nhưng hệ thống hiện thời không cho phép
![image](https://github.com/dylan751/sushi/assets/8079397/bf064df8-c5f1-4322-942e-cbba2ee50c3e)

## Đề xuất
 Bắt buộc phải cho phép kí tự **-** (có ý nghĩa là Không có VAT, giống như 0%, nhưng buộc phải để kí tự - ), và **0%**
 Thậm chí dùng kí tự - như là giá trị mặc định.

**Comment by dylan751** [comment]
Ở UI, đã cho phép người dùng nhập ký hiệu '-' hoặc '0' cho trường `tax` (mặc định ký hiệu '-' được coi là null rồi)
