### ISSUE TITLE
Feature: trang landingpage tĩnh

### ISSUE THREAD

**Issue by neittien0110** [dylan751/sushi#221]
## Mô tả

Trang landingpage **tĩnh** giới thiệu sản phẩm bao gồm:
1. Mô tả sản phẩm trong 3 câu
2. Tính năng chính
3. Video demo
4. Link dùng thử (chính là link sản phẩm)
5. Các gói dịch vụ
  5a. Các gói dịch vụ dành cho tổ chức
   - [ ] Free: Giới hạn 3 project; 5 category/project; 2 user;  Tên tổ chức luôn giống nhau và là HDWallet.
   - [ ] Low cost High effective: Giới hạn 20 projects; không giới hạn category;  5 users; 500.000đ/tháng
   - [ ] Teamwork:  Giới hạn 10 projects; giới hạn 10 category/project;  Không giới hạn users; 500.000đ/tháng
   - [ ] Professional: Không giới hạn, 1.000.000đ/tháng
5b. Các gói dịch vụ dành cho  Outsourced Accouting (Kế toán thuê ngoài): 
   - [ ] Free: *tương tự như trên*
   - [ ] Freelance: Không giới hạn projects; không giới hạn category; giới hạn 2 user; 200.000đ/tháng
 5c. Dịch vụ gia tăng:
   - [ ]  Hiển thị tên tổ chức thay thế cho tên của hệ thống HDWallet: 50.000đ/tháng
   - [ ] Hiển thị logo tổ chức thay thế cho logo của hệ thống HDWallet: 50.000đ/tháng 
6. Các lời khuyên
- Nếu bạn là một startup, một doanh nghiệp nhỏ, hãy sử dụng gói Free là ổn thỏa. Trường hợp có phát sinh dự án nhiều quá, bạn chỉ việc ẩn(visible) các dự án cũ là được. Là chủ startup/doanh nghiệp,bạn cũng có thể tận dụng tài nguyên 2 users để bổ sung 1 kế toán, hoặc kế toán thuê ngoài.
- Nếu bạn đã là một doanh nghiệp có nguồn thu ổn định và lượng dự án lớn, hãy sử dụng gói  Low cost High effective, để chia sẻ công việc giữa nhiều thành viên của bộ phận kế toán, đồng thời dễ dàng kiểm soát các định mức và số liệu trực tuyến 
- Nếu bạn là kế toán thuê ngoài, bạn có thể sử dụng gói Freelance và khuyến khích các doanh nghiệp khách hàng của bạn mở tài khoản Free. Như vậy bạn sẽ quản trị một cách độc lập thông tin của từng khách hàng, mà không bị lẫn số liệu.

PS: luôn để số user >=2 để thể hiện ưu thế teamwork của hệ thống, đặc biệt là khả năng Kế toán thuê ngoài.
PS: 2 hình thức tính phí dịch vụ theo tổ chức và theo cá nhân là khá chồng chéo. CHƯA CÓ GIẢI PHÁP TRIỆT ĐỂ.

## Đề nghị
- Hệ thống web chính với NGINX chỉ cần cấu hình thư mục static để trỏ tới 1 thư mục LANDINGPAGE cố định
- Website Landingpage phải được thiết kế bằng công cụ độc lập như [Mobirise](https://mobirise.com/) chứ không phải viết code. Lý do là nội dung của Landingpage phải do bộ phận Kinh doanh thay đổi, chứ không phải do bộ phàn Kỹ thuật

**Comment by dylan751** [comment]
Đã thực hiện và deploy trên: https://udon-kappa.vercel.app/
