### ISSUE TITLE
Không Submit được Role chỉnh sửa

### ISSUE THREAD

**Issue by neittien0110** [dylan751/sushi#239]
## Mô tả
1. Truy cập vào Role của 1 quyền nào đó. Ví dụ role **Member** của tổ chức UNC <https://hdwallet.toolhub.app/unc/roles/>
2. Thay đổi các quyển Right như Create/Edit
3. Nút Submit vẫn bị Disable.
![image](https://github.com/dylan751/sushi/assets/8079397/a6ab0626-0ba5-4a3d-9fdb-874d2ec65486)

**Comment by dylan751** [comment]
@neittien0110 Role `Admin` và `Member` là 2 role mặc định của hệ thống, ko cho phép sửa ạ. Người dùng có thể tạo những role mới và sửa tuỳ ý bình thường

**Comment by neittien0110** [comment]
Đúng thế
