### ISSUE TITLE
Bug: không thể quay trở lại giao diện Danh sách hóa đơn sau khi soạn xong 1 hóa đơn

### ISSUE THREAD

**Issue by neittien0110** [dylan751/sushi#243]
## Mô tả 
Do không có breadcrumb nên không thể quay trở lại **giao diện Danh sách hóa đơn**
![image](https://github.com/dylan751/sushi/assets/8079397/45838c1c-6c5e-49f9-a39a-d5cdb06bbca8)

**Comment by dylan751** [comment]
Sau khi soạn xong hoá đơn, người dùng có thể vào Sidebar phần `Invoice -> List` để truy cập danh sách hoá đơn
