### ISSUE TITLE
bug: bị xô lệch ở trang web để in hóa đơn 

### ISSUE THREAD

**Issue by neittien0110** [dylan751/sushi#244]
## Mô tả:
  - thực hiên chức năng in hóa đơn
  - trang web để print hóa đơn thì ổn nhưng
  - dàn trang print của trang đó thì xô lệch
![image](https://github.com/dylan751/sushi/assets/8079397/293ab30e-eb99-416f-a956-d276589e4473)
![image](https://github.com/dylan751/sushi/assets/8079397/db7eb0b0-7c25-48f7-a0a6-030ef313756b)

## Gợi ý:
 - Thiết lập khổ giấy A4
Tham khảo css: https://stackoverflow.com/questions/16649943/css-to-set-a4-paper-size

**Comment by dylan751** [comment]
Closed here: https://github.com/dylan751/sushi/pull/248
