### ISSUE TITLE
Tính tổng tiền theo Category Name

### ISSUE THREAD

**Issue by neittien0110** [dylan751/sushi#254]
## Mô tả

    Cần các thống kê theo Category của tất cả các dự án.   Ví dụ: Tính tổng chi phí đi lại của tất cả các Project như A12, Bpre, etc.

## Hiện trạng

   Chỉ thống kê theo từng dự án

## Giải pháp gợi ý

Cần phải tìm một định danh của Category để sao cho mọi dự án đều dùng chung ==> Thay vì sử dụng CategoryID thì hãy sử dụng **CategoryName**, và đưa ra qui tắc yêu cầu khách hàng phải đặt tên Category giống nhau nếu muốn truy vấn thông giữa các dự án.

**Comment by dylan751** [comment]
Đã thêm chức năng thống kê cho toàn bộ `organization`, theo `income` & `expense`.
Yêu cầu: Các `Category Name` trùng nhau trong 1 tổ chức sẽ được tính tổng lại

![image](https://github.com/user-attachments/assets/616e9566-515f-4781-922f-8132b8dde7b8)
